<script setup>
import { ref } from 'vue'
import AdminLayout from '../../layouts/AdminLayout.vue'
import QRScanner from '../../components/QRScanner.vue'

const scanning = ref(false); const scanMessage = ref('')
const handleScan = (value) => { scanMessage.value = value ? 'Participant found. Review the attendee details before confirming check-in.' : '' }
</script>

<template><AdminLayout><section class="checkin-workspace"><header class="checkin-heading"><div><p class="admin-eyebrow">Live desk · today</p><h1>Check-in participants</h1><p>Scan a participant QR code to verify registration and mark attendance.</p></div><span class="live-indicator"><i></i> Live check-in desk</span></header><div class="checkin-layout"><article class="scanner-panel"><div class="scanner-panel-heading"><div><h2>Scan participant QR</h2><p>Position the code inside the frame. The camera will scan automatically.</p></div><button type="button" class="secondary-button" @click="scanning = !scanning">{{ scanning ? 'Stop scanner' : 'Start scanner' }}</button></div><div v-if="scanning" class="scanner-shell"><QRScanner @scan="handleScan" /><div v-if="scanMessage" class="scan-success">✓ {{ scanMessage }}</div></div><div v-else class="scanner-placeholder"><div class="scanner-frame">⌗</div><strong>Scanner is paused</strong><p>Start the scanner when you are ready to check in attendees.</p><button type="button" class="primary-button" @click="scanning = true">Start scanner</button></div></article><aside class="checkin-summary"><p class="admin-eyebrow">Event summary</p><h2>Community Tech Summit</h2><div class="checkin-progress"><div><span>Checked in</span><strong>0 / 0</strong></div><div class="progress-bar"><span></span></div></div><div class="checkin-stats"><div><small>Expected</small><strong>0</strong></div><div><small>Checked in</small><strong>0</strong></div><div><small>Remaining</small><strong>0</strong></div></div><RouterLink to="/admin/events" class="text-link">Change event →</RouterLink></aside></div><section class="checkin-table-panel"><header><div><p class="admin-eyebrow">Attendance log</p><h2>Recent check-ins</h2></div><button type="button" class="secondary-button">Export log</button></header><div class="recent-empty"><span>✓</span><div><strong>No check-ins yet</strong><p>Scanned participants will appear here with their check-in time.</p></div></div></section></section></AdminLayout></template>
