<script setup>
import { computed } from 'vue'
import UserLayout from '../../layouts/UserLayout.vue'
import QRCodeDisplay from '../../components/QRCodeDisplay.vue'
import { useRegistrationStore } from '../../stores/registration'

const store = useRegistrationStore()
const registration = computed(() => store.current)
const qrValue = computed(() => registration.value?.qr_token || registration.value?.registration_code || 'registration-confirmation')
const downloadQr = () => { const canvas = document.querySelector('.confirmation-qr canvas'); if (!canvas) return; const anchor = document.createElement('a'); anchor.download = `${registration.value?.registration_code || 'registration'}-qr.png`; anchor.href = canvas.toDataURL('image/png'); anchor.click() }
const addToCalendar = () => { const start = registration.value?.event_date ? new Date(registration.value.event_date) : new Date(); const end = new Date(start.getTime() + 2 * 60 * 60 * 1000); const format = (value) => value.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'; const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(registration.value?.event_name || 'Event')}&dates=${format(start)}/${format(end)}&location=${encodeURIComponent(registration.value?.event_location || '')}`; window.open(url, '_blank', 'noopener') }
</script>

<template><UserLayout><section class="confirmation-page"><div class="confirmation-hero"><span class="confirmation-check">✓</span><p class="eyebrow">Registration confirmed</p><h1>Registration successful!</h1><p>Your place is reserved. Keep this confirmation QR code ready for event check-in.</p></div><div v-if="registration" class="confirmation-layout"><article class="confirmation-details"><p class="field-label">Event details</p><h2>{{ registration.event_name }}</h2><div class="confirmation-info"><div><span>Registration ID</span><strong>{{ registration.registration_code }}</strong></div><div><span>Participant</span><strong>{{ registration.full_name || 'Attendee' }}</strong></div><div><span>Event date</span><strong>{{ registration.event_date || 'To be confirmed' }}</strong></div><div><span>Location</span><strong>{{ registration.event_location || 'To be confirmed' }}</strong></div></div></article><article class="confirmation-pass"><p class="field-label">Participant pass</p><div class="confirmation-qr"><QRCodeDisplay :value="qrValue" /></div><p>Present this QR code at check-in.</p><button type="button" class="button" @click="downloadQr">Download QR code</button></article></div><div v-else class="confirmation-details"><h2>Registration details unavailable</h2><p>Return to your account to view your registrations.</p></div><footer class="confirmation-actions"><RouterLink class="button" to="/me">View registration</RouterLink><button type="button" class="link-button" @click="addToCalendar">Add to calendar</button></footer></section></UserLayout></template>
